a = ('Evaluación N°1 Programación y Redes Virtualizadas')
b = ('Integrantes:')
c = ('Wilder Ciriaco')
e = ('Claudia Peña')
d = ('Hans Rumian')
print((a) + '\n' + (b) + '\n' + (c) + '\n' +(e) + '\n'+ (d))